### ISSUE TITLE
[Feature]: update weather status on newTab

### ISSUE THREAD

**Issue by realDarkCode** [ProCodify/ProTab#4]
### Tasks: 

- [x] Find suitable weather icons
- [x] Fetch Weather via API 
- [x] Update weather icon and status

**Comment by realDarkCode** [comment]
@ProgrammerRhythm fix the weather icon and temperature broken style
![image](https://user-images.githubusercontent.com/72726603/184535338-a9b56171-b464-430b-93cc-c29a4a8c1844.png)
